const Endpoints = {
    FETCH_SCHOCATEGORY:"scholar/schoCat",
    CHANGE_PASSWORD:"userProf/ChangePassword",
    FETCH_USER_BY_ID:"userProf/UserAccounts",
    FETCH_ACCOUNTS:"userProf/UserAccounts",
    FETCH_SCHOLAR_CATEGORY:"scholar/schoCat",
    CREATE_SCHOLAR:"scholar/createScho",
    FETCH_NEWS:"news/newsinfo",
    FETCH_ADMIN:"admin/login",
    LOGIN_USER:"user/login",
    CHANGE_PROFILE:'userProf/profile',
    FETCH_ANNOUNCEMENTS:'announce/Announced',
    CREATE_APPFORM:'personalinfo/create',
    FETCH_PERSONALINFO:'personalinfo/PA/',
    FETCH_PROFILEBYUSER: 'userProf/getPROFILE/',
    CREATE_REGISTRY: 'user/create',
    FETCH_USER:'user/',
    FETCH_TRIVIA: 'trivia/TriviaoftheDay',
    UPLOAD_REQUIREMENTS: 'requirements/uploadRequirement',
    LIST_REQUIREMENTS: 'documents/Requirements',
    FETCH_SUBMITTED: 'requirements/',
    EDIT_SUBMITTED: 'requirements/Edit',
    DELETE_SUBMITTED: 'requirements/Delete',
    FETCH_FAMLIST: 'personalinfo/',
    FETCH_APPLICANTSINFO: 'personalinfo/ApplicantFdetails/',
    REGSITRY_OTP: 'OTP/RegistryOtp',
    RESEND_OTP: 'OTP/ResendOtp',
    VALIDATE_OTP: 'OTP/ValidateOtp',
    VALIDATE_USEROTP: 'OTP/ValidateUserOtp',
    FETCH_USERACCS: 'OTP/ForgotPassword/',
    GENERATE_OTP: 'OTP/GenerateOtp',
    CHANGE_PASSWORDBYOTP: 'OTP/ChangePassword',
    FETCH_BMCCSCHOLARINFO: 'BMCCScholar/SchoInfo/',
    FETCH_USERAPPOINTMENT: 'Appointment/appointmentSched/',
    USER_LOGOUT:'user/Logout',
}

export default Endpoints